const quotes = [
  "L'étrange créature marche dans la forêt obscure.",
  "L'océan rugit contre les rochers escarpés.",
  "L'énigmatique message est découvert sur le mur.",
  "L'arôme du café fraîchement moulu remplit la cuisine.",
  "L'escalier en colimaçon mène au sommet de la tour.",
  "Le clair de lune éclaire les toits de la ville.",
  "Le silence résonne dans la grotte sombre.",
  "La brise légère agite les feuilles des arbres.",
  "La fumée s'élève de la cheminée dans le ciel nocturne.",
  "La pluie tambourine contre les fenêtres de la maison.",
  "Le parfum des fleurs sauvages envahit l'air.",
  "Le grondement du tonnerre se fait entendre à l'horizon.",
  "La lueur des étoiles scintille dans le ciel nocturne.",
  "L'écho des pas résonne dans les rues désertes.",
  "Le bruit des vagues se brisant sur la plage est apaisant.",
  "La lumière des bougies vacille dans la pièce sombre.",
  "Le gazouillis des oiseaux accompagne le lever du soleil.",
  "La chaleur du feu de camp réchauffe les mains glacées.",
  "Le fracas des vagues contre les rochers est assourdissant.",
  "johndoe1@gmail.com",
  "jane.doe@yahoo.com",
  "michael.brown@hotmail.com",
  "sarah_johnson@outlook.com",
  "chris.wilson@aol.com",
  "emma_b@gmail.com",

  "brandon.s@gmail.com",
  "jennifer.t@yahoo.com",
  "matthew.r@hotmail.com",
  "samantha.g@outlook.com",
  "joseph.l@aol.com",

  "4, rue du Faubourg Saint-Honoré, 75008 Paris",
  "5, boulevard Saint-Germain, 75006 Paris",
  "6, place de la Concorde, 75008 Paris",
  "7, rue de Rivoli, 75001 Paris",
  "8, rue de la Paix, 75002 Paris",
  "9, avenue des Ternes, 75017 Paris",
  "10, rue de Passy, 75016 Paris",
];

export { quotes };
